sudo: required
language: java
jdk:
- openjdk11
before_install:
- openssl aes-256-cbc -K $encrypted_0cae374807e3_key -iv $encrypted_0cae374807e3_iv
  -in travis/helseci.key.enc -out travis/helseci.key -d
- git clone https://github.com/navikt/github-apps-support.git
- export PATH=`pwd`/github-apps-support/bin:$PATH
- export GH_TOKEN=$(generate-installation-token.sh `generate-jwt.sh ./travis/helseci.key
  $GITHUB_APP_ID`)
- export COMMIT_SHORT=$(git rev-parse --short HEAD)
- export ORIGINAL_COMMITTER=$(git log -1 --pretty=format:'%an <%ae>')
- echo -e "machine github.com\n  login $GH_TOKEN" > ~/.netrc
- rm "${JAVA_HOME}/lib/security/cacerts"
- ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
script:
- "./mvnw versions:set -DnewVersion=$COMMIT_SHORT"
- "./mvnw clean package"
- |
  set -e
  if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then

    git config user.name team-helse[bot]
    git config user.email team-helse[bot]@users.noreply.github.com

    git add pom.xml
    git commit -m "Bump version [skip ci]" -m "Caused by $TRAVIS_BUILD_WEB_URL" --author "$ORIGINAL_COMMITTER"

    git push https://x-access-token:$GH_TOKEN@github.com/navikt/nare.git HEAD:master
  fi
env:
  global:
    secure: kyPnGl1zygrL1CY7aCfOAfPuTwsuadEr8UAyqGsRyqEizhjkVMz12hu6I5An3wwviM6RGppnl52P4Tx96gMKmUDjygHcNx+ci95eloucxQoKjQ1krEvpLmS9KbaGj9uVkqiFVlvfVTi0A3EL2nTn2Sf0p/dtEnao4U9gXpk151IodD+j8K98+okMeKwGVpRy9N0qJrHobdnvsCSRCKaNoAupg0VDmpCQSdycHbmblXUFAHnMHpp3VzkU1DwBKrOwOP4SuE+Dt0qY2Aa8dbfUOfYt5s90/pHxll33cWlfkcEqHRRrPwn8wPov5nYjf/EnMD+eHPK5MsN960LP0TyWn9CGyybxw7QLsQMyZhpggsSsF601hfxYlVQtiPAVvI8sLS7yPNN22QQbLG/pX0Df1hM0KQKcjPu8UesA4bBRukwZpJnSm+5sTYi6d9zM9WxjqA8+ABywVm6yHgbUrnhp3t8C3/ztQRJmmowJ/IkiPKCzTKBiZz5EsgwGuYyn414lfppNc9pdOYR06NVybAglce0J9NkvoUf7mI9C93R7TLNK53s1aIpt8FG3hm1UAFh354/uthR+FdloE80qiokvZCJcNLEjMBBFGsPby6FTZ6afI/J5MeNGeQlSWXva9i7nW0ebqLZVXTHMtiBAMJmgBDhMK/PWWYXTY04XlR9Eif0=
notifications:
  slack:
    secure: TcSkw7CXSOZOU6P/bGpQp+wcQRBBxSqfhOt0bf/tPJ/1TkJ1a+OmIKdCunRhWugQq1LpqBu/ApxFuRc0NLlkf+f5PZeMVLhThhWw0rNVtMWBfLS7LF7DNDoeZRAp5mgKi9fb1h42nlDqpF2cE+se7E4T6Mr1HJWgNr3DCZEOb5d31dmNWYkmvd+V5noToIsyM9y70dLBofz8fGAZqQcnN/sfjfZ9AdciJJqWosgfkIksDMWL336WmGzIWXP+M+vsWBw5sFvulRImz1jCrFV44bWuz3ppFj/X6sEI/u4Bihak0aRWNyjGjkn2kQoxywmZdfbls22vOf7VYvqJRojKxakr3aQ8PBjWK1Z7nagEyOmquTjH00GDAf4srcVBJhDivgUJAwh5G9pPJOUJSheqhuWvOAkKeWytznAbx1oY3I+VsKjGral5D02T3ewVOBA4cTijqF6C5khWFS9kDBhhfOo3UX+9OuOyGPcekbA41PbDXyyeyJqyf51I2CxrQw1HsLwUTYduki6kPpSrbisWQTR/TePyx8iJ2RjSdLriT0qFmPlT6RvS/3DG4Pp/z8sSCFqt48PR0Mt9iOr0vAcxSnWR8s01/E1hrTJ7gRxrv559v6UZW937X2bHWcUzXB1xaRdnyT/0/eqx4nAiMHxCzEYFHu8tXhlyZYJvNkumyAQ=
